### ISSUE TITLE
[wholeBodyInterface] General Redesign 

### ISSUE THREAD

**Issue by traversaro** [robotology/codyco-modules#38]
A lot of aspects of the `wholeBodyInterface` need a redesign: this issue works as an entry point to all other issues related to `wholeBodyInterface`. 
- Core issues:
  - [x] New ID representation : https://github.com/robotology/codyco/issues/6
  - [ ] Document expected size everywhere : https://github.com/robotology/codyco/issues/26
  - [ ] Document units everywhere: https://github.com/robotology/codyco/issues/14
    - [ ] Always use international system 
  - [ ] Difference between `link` and `frame` concepts : https://github.com/robotology/codyco/issues/39
  - [x] Initialization should be done always in `init()` functions, not in constructors : https://github.com/robotology/codyco/issues/63
  - [ ] WBI implementations should be thread safe? https://github.com/robotology/codyco/issues/64
- `iWholeBodyStates` related:
  - [ ] Set priors in `iWholeBodyStates` : https://github.com/robotology/codyco/issues/10
  - [x] Add/remove of estimates is broken : https://github.com/robotology/codyco/issues/18
    - [x] Add/remove of estimates should be permitted just at configuration time, not at runtime
- `iWholeBodyModel` related:
  - [ ] General redesign of `iWholeBodyModel` : https://github.com/robotology/codyco/issues/27
- `iWholeBodyActuactors` related:
  - [ ] General `iWholeBodyActuactors` issues : https://github.com/robotology/codyco/issues/36
    - All interfaces are relative joints, while open loop is related to motors.
  -  [ ] How `iWholeBodyActuactors` should deal with errors : https://github.com/robotology/codyco/issues/15
- `iWholeBodySensors` related:
  - [ ] How to specify available sensors in `iWholeBodySensors` : https://github.com/robotology/codyco/issues/17
  - [ ] Blocking sensor reading calls should have a optional timeout : https://github.com/robotology/codyco/issues/46

**Comment by traversaro** [comment]
I think that this issue can be closed, as the idea is to move away from the `wholeBodyInterface` towards a direct use of `ControlBoardRemapper`, `iDynTree::KinDynComputations` and future YARP interface to read inertial sensors https://github.com/robotology/yarp/issues/1273 .
